provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

sources:
  - gateway-httproute
  - gateway-grpcroute

extraArgs:
  - --exclude-target-net=10.0.0.0/8

policy: sync

registry: txt
txtOwnerId: oci-oke

logLevel: info
logFormat: json

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
