apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-svc-image-signature
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-svc-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  verify-images: "true"
      verifyImages:
        - imageReferences:
            - "ghcr.io/ggingggang/svc-*"
          failureAction: Enforce
          mutateDigest: false
          verifyDigest: false
          imageRegistryCredentials:
            secrets:
              - ghcr-pull
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE92VHKpaJ8cuHBSZX0fcD55oSbdMq
                      W8gApA8m6UHPHvCoj/NmSfJXGRLBV+IcJW/9Wm6ZhIovIEJUN87LVHv3hg==
                      -----END PUBLIC KEY-----
                    rekor:
                      ignoreTlog: true
