apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __SVC__
  namespace: cicd
spec:
  project: apps
  source:
    repoURL: https://github.com/__ORG__/k8s-gitops.git
    targetRevision: main
    path: manifests/__SVC__
  destination:
    server: https://kubernetes.default.svc
    namespace: __SVC__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
