apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-httproute
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
    targetRevision: main
    path: kubernetes/platform/argocd
    directory:
      recurse: false
      include: "httproute.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
