apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.6
      helm:
        valueFiles:
          - $values/kubernetes/infra/cert-manager/values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
