apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: platform
  source:
    repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
    targetRevision: main
    path: kubernetes/platform/kyverno/policies
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
