apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.8.2
      helm:
        valueFiles:
          - $values/kubernetes/platform/kyverno/values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
