apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 3.13.1
      helm:
        valueFiles:
          - $values/kubernetes/infra/metrics-server/values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
