apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: cicd
spec:
  project: platform
  source:
    repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
    targetRevision: main
    path: kubernetes/infra/namespaces
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
