apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform
  sources:
    - repoURL: https://nats-io.github.io/k8s/helm/charts/
      chart: nats
      targetRevision: 2.14.2
      helm:
        valueFiles:
          - $values/kubernetes/platform/nats/values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
