apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 1.0.1
      helm:
        valueFiles:
          - $values/kubernetes/platform/kafka/operator.values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
