apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: ztunnel
      targetRevision: 1.29.3
      helm:
        valueFiles:
          - $values/kubernetes/infra/istio/ztunnel.values.yaml
    - repoURL: https://github.com/GGingGGang/oci-always-free-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
