apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-wildcard
  namespace: istio-system
spec:
  secretName: public-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ggang.cloud
  dnsNames:
    - ggang.cloud
    - "*.ggang.cloud"
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
