apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: cicd
spec:
  project: apps
  source:
    repoURL: https://github.com/GGingGGang/k8s-test-core-server.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
