name: yaml-lint

on:
  push:
    branches: [main]
    paths:
      - "kubernetes/**"
      - ".yamllint.yaml"
      - ".github/workflows/yaml-lint.yml"
  pull_request:
    paths:
      - "kubernetes/**"
      - ".yamllint.yaml"
      - ".github/workflows/yaml-lint.yml"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes
    steps:
      - uses: actions/checkout@v4
      - run: pipx install yamllint
      - run: yamllint --strict -c ../.yamllint.yaml .
